import {
  FaAward,
  FaBook,
  FaBookOpen,
  FaBriefcase,
  FaBullhorn,
  FaCertificate,
  FaChalkboardTeacher,
  FaChartLine,
  FaCheckCircle,
  FaCloud,
  FaCode,
  FaCogs,
  FaCompass,
  FaCube,
  FaCubes,
  FaDatabase,
  FaDesktop,
  FaEnvelope,
  FaFacebookF,
  FaFileAlt,
  FaFlask,
  FaGlobe,
  FaGraduationCap,
  FaHandshake,
  FaHeadset,
  FaIdCard,
  FaInstagram,
  FaLandmark,
  FaLaptopCode,
  FaLightbulb,
  FaLink,
  FaLinkedinIn,
  FaLock,
  FaMapMarkerAlt,
  FaMicrochip,
  FaMobile,
  FaMobileAlt,
  FaMoneyCheckAlt,
  FaPaintBrush,
  FaPenNib,
  FaPhoneAlt,
  FaPlug,
  FaPrint,
  FaRocket,
  FaSearch,
  FaServer,
  FaShieldAlt,
  FaStar,
  FaTelegramPlane,
  FaTools,
  FaTshirt,
  FaTwitter,
  FaUniversity,
  FaUserCheck,
  FaUserGraduate,
  FaUsers,
  FaWhatsapp,
  FaWindows,
  FaYoutube,
} from "react-icons/fa";

/**
 * Icons the admin can pick for section items. The database stores the
 * name (e.g. "FaGlobe"); add an import + entry here to offer a new icon.
 */
export const ICONS = {
  FaAward,
  FaBook,
  FaBookOpen,
  FaBriefcase,
  FaBullhorn,
  FaCertificate,
  FaChalkboardTeacher,
  FaChartLine,
  FaCheckCircle,
  FaCloud,
  FaCode,
  FaCogs,
  FaCompass,
  FaCube,
  FaCubes,
  FaDatabase,
  FaDesktop,
  FaEnvelope,
  FaFacebookF,
  FaFileAlt,
  FaFlask,
  FaGlobe,
  FaGraduationCap,
  FaHandshake,
  FaHeadset,
  FaIdCard,
  FaInstagram,
  FaLandmark,
  FaLaptopCode,
  FaLightbulb,
  FaLink,
  FaLinkedinIn,
  FaLock,
  FaMapMarkerAlt,
  FaMicrochip,
  FaMobile,
  FaMobileAlt,
  FaMoneyCheckAlt,
  FaPaintBrush,
  FaPenNib,
  FaPhoneAlt,
  FaPlug,
  FaPrint,
  FaRocket,
  FaSearch,
  FaServer,
  FaShieldAlt,
  FaStar,
  FaTelegramPlane,
  FaTools,
  FaTshirt,
  FaTwitter,
  FaUniversity,
  FaUserCheck,
  FaUserGraduate,
  FaUsers,
  FaWhatsapp,
  FaWindows,
  FaYoutube,
};

export const ICON_NAMES = Object.keys(ICONS);

export const DEFAULT_ICON = FaStar;

/** Accepts an icon name from the DB or an icon component (static fallback). */
export function resolveIcon(icon) {
  if (!icon) return DEFAULT_ICON;
  if (typeof icon === "string") return ICONS[icon] ?? DEFAULT_ICON;
  return icon;
}

/** "FaGraduationCap" -> "Graduation Cap" */
export function iconLabel(name) {
  return name.replace(/^Fa/, "").replace(/([a-z])([A-Z])/g, "$1 $2");
}
